version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: OrderManagerUser
      POSTGRES_PASSWORD: OrderManagerPass
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  springboot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: order-manager-spring-api
    env_file:
      - .env.example.dev
    ports:
      - 8000:8080

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: