name: Build
on:
  push:
    branches:
      - master
jobs:
  BuildDeploy:
    name: BuildDeploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn package -DskipTests=true
